INSERT INTO CONVIDADO (ID, NOME, QUANTIDADE_ACOMPANHANTES) VALUES (1, 'Pedro', 2);
INSERT INTO CONVIDADO (ID, NOME, QUANTIDADE_ACOMPANHANTES) VALUES (2, 'Maria', 3);
INSERT INTO CONVIDADO (ID, NOME, QUANTIDADE_ACOMPANHANTES) VALUES (3, 'Ricardo', 1);
